### ISSUE TITLE
Upload failure 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'

### ISSUE THREAD

**Issue by ltog** [openstreetcam/upload-scripts#86]
While trying to upload some EXIF-tagged pictures the upload stopped and I got the error message shown below. I would expect that the script is able to handle errors gracefully without exiting...

Some infos:

- I used version 600c3d4f90970d675490a3a398ec66ded201b9d4 with option `-w 20`
- Python version is 3.6.7 on Ubuntu

```
Traceback (most recent call last):
  File "osc_tools.py", line 212, in <module>
    main()
  File "osc_tools.py", line 22, in main
    args.func(args)
  File "osc_tools.py", line 119, in upload_command
    upload_manager.start_upload()
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_uploader.py", line 57, in start_upload
    success, sequence = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_uploader.py", line 107, in upload
    self._visual_items_upload_with_operation(sequence, visual_item_upload_operation)
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_uploader.py", line 144, in _visual_items_upload_with_operation
    uploaded, index = completed_event.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_uploader.py", line 234, in upload
    photo.path)
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_api_gateway.py", line 430, in upload_photo
    return OSCApi.__upload_response_success(response, "photo", photo.sequence_index), None
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/osc_api_gateway.py", line 110, in __upload_response_success
    json_response = response.json()
  File "/home/bozo/Desktop/PROJEKTE/openstreetcam-upload-scripts/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by pkoby** [comment]
I would upload more willingly if this didn't happen innumerable times every sequence. This (and other errors) has been present since I started uploading a few months ago.

**Comment by panthersdude2001** [comment]
Same problem here. When uploading Mapillary images to OSC, it gives me this message.
Expecting value: line 1 column 1
With this Traceback (most recent call last):
  File "osc_tools.py", line 212, in <module>
    main()
  File "osc_tools.py", line 22, in main
    args.func(args)
  File "osc_tools.py", line 119, in upload_command
    upload_manager.start_upload()
  File "C:\Users\snowc\Downloads\upload-scripts\osc_uploader.py", line 57, in start_upload
    success, sequence = future.result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\snowc\Downloads\upload-scripts\osc_uploader.py", line 107, in upload
    self._visual_items_upload_with_operation(sequence, visual_item_upload_operation)
  File "C:\Users\snowc\Downloads\upload-scripts\osc_uploader.py", line 144, in _visual_items_upload_with_operation
    uploaded, index = completed_event.result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\snowc\Downloads\upload-scripts\osc_uploader.py", line 234, in upload
    photo.path)
  File "C:\Users\snowc\Downloads\upload-scripts\osc_api_gateway.py", line 430, in upload_photo
    return OSCApi.__upload_response_success(response, "photo", photo.sequence_index), None
  File "C:\Users\snowc\Downloads\upload-scripts\osc_api_gateway.py", line 110, in __upload_response_success
    json_response = response.json()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Strubbl** [comment]
The most recent commits catch this JSONDecodeError.
