### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by panthersdude2001** [openstreetcam/upload-scripts#94]
When uploading using the script, it gives me this message
Traceback (most recent call last):
  File "osc_tools.py", line 212, in <module>
    main()
  File "osc_tools.py", line 22, in main
    args.func(args)
  File "osc_tools.py", line 93, in upload_command
    sequences = discoverer.discover(path)
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\osc_discoverer.py", line 113, in discover
    sequence = self.create_sequence(path)
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\osc_discoverer.py", line 128, in create_sequence
    (visual_data, data_type) = self.visual_data.discover(path)
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\visual_data_discover.py", line 112, in discover
    metadata_photos = parser.all_photos()
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\metadata_parser_legacy.py", line 33, in all_photos
    tmp_item = self._get_metadata_item(elements)
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\metadata_parser_legacy.py", line 192, in _get_metadata_item
    photo = self._get_photo_item(elements)
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\metadata_parser_legacy.py", line 214, in _get_photo_item
    video_index = self._value(elements, 'video_index')
  File "C:\Users\snowc\Downloads\Compressed\upload-scripts-master\metadata_parser_legacy.py", line 159, in _value
    if elements[self._metadata_legacy_format[key]] != '':
IndexError: list index out of range
@alrs @mfa @jalessio @mstock @ToeBee can somebody please solve this issue? Trying to upload an old sequence from August.

**Comment by panthersdude2001** [comment]
Still experiencing the error, and this program seems to no longer work. @chip-grab any words on when this list index out of range error being fixed?

**Comment by panthersdude2001** [comment]
![list index out of range](https://user-images.githubusercontent.com/44646536/76578817-2b2aed80-64a0-11ea-9fd7-1507de7fa4fe.png)
here is the error im getting

**Comment by salabogdan** [comment]
@panthersdude2001, please provide the track.txt.zip or track.txt file in order to debug this problem.

**Comment by panthersdude2001** [comment]
Ok, I got it to work, but not with this sequence. It seems to be the sequence is not full, and has to be full.

**Comment by panthersdude2001** [comment]
[track.txt](https://github.com/openstreetcam/upload-scripts/files/4533671/track.txt)

**Comment by panthersdude2001** [comment]
And here is the problematic file!
![image](https://user-images.githubusercontent.com/44646536/80287296-cac5d780-86fe-11ea-9e4c-b0e68e696698.png)
[track.txt.gz](https://github.com/openstreetcam/upload-scripts/files/4533726/track.txt.gz)

**Comment by panthersdude2001** [comment]
Found the problem. For users that are experiencing this problem:
1. Go to the track.txt and remove all the suspicious characters like yyyyy
2. Save the track.txt and add it to a gzip archive
3. Upload again.
Now it works.
Closing
